[package]
name = "sifis-api"
version = "0.0.0"
edition = "2021"
description = "SIFIS-Home Third-party API"
license = "MIT"
repository = "https://github.com/sifis-home/sifis-rust"
keywords = ["SIFIS-Home"]

[dependencies]

