[package]
name = "sifis"
version = "0.0.0"
edition = "2021"
description = "SIFIS-Home Web of Things (WoT) Servients"
license = "MIT"
repository = "https://github.com/sifis-home/sifis-rust"
keywords = ["wot", "WebofThings"]

[dependencies]

